- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Creates directory 
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend tar.gz file and unzip it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "deploy backend app to new location"
  become: true
  copy:
    src:  /root/project/backend/.env
    dest: /home/ubuntu/backend/

- name: "Fix critical dependencies"
  become: true
  command: npm audit fix & npm audit fix --audit-level=critical --force
  args:
    chdir: /home/ubuntu/backend

- name: "build application"
  become: true
  command: npm run build 
  args:
    chdir: /home/ubuntu/backend

- name: "Run migrations"
  become: true
  command: npm run migrations
  args:    
    chdir: /home/ubuntu/backend

# pm2 will automatically restart your application if it crashes
# pm2 will keep a log of your unhandled exceptions /home/<user>/.pm2/logs/app-err.log.
# learn more: https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps
- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls